CREATE DATABASE IF NOT EXISTS music DEFAULT CHARSET=utf8;
USE music;
CREATE TABLE IF NOT EXISTS `group`(`GROUP_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,`GROUP_NAME` VARCHAR(50) NOT NULL,PRIMARY KEY(`GROUP_ID`) USING BTREE) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `genre`(`GENRE_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,`GENRE_NAME` VARCHAR(30) NOT NULL,PRIMARY KEY(`GENRE_ID`) USING BTREE) DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `group_genre`(`GROUP_GENRE_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT, PRIMARY KEY(`GROUP_GENRE_ID`),`GROUP_ID` INT(10) UNSIGNED NOT NULL,`GENRE_ID` INT(10) UNSIGNED NOT NULL, CONSTRAINT `FK_GROUP_ID` FOREIGN KEY(`GROUP_ID`) REFERENCES `group`(`GROUP_ID`) ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT `FK_GENRE_ID` FOREIGN KEY(`GENRE_ID`) REFERENCES `genre`(`GENRE_ID`) ON DELETE CASCADE ON UPDATE CASCADE) DEFAULT CHARSET=utf8;
